-- Bulk insert all vocabulary words
INSERT INTO cards (german, french, status, learning_correct_count) VALUES
('jdm. auf den Fersen sein', 'talonner qn', 'learning', 0),
('die Rippe', 'la côte', 'learning', 0),
('wackeln', 'frétiller', 'learning', 0),
('Secondhandladen', 'le magasin d''occasions', 'learning', 0),
('das Hündchen', 'le toutou', 'learning', 0),
('jdm. Schwierigkeiten/Scherereien machen', 'faire des histoires à qn', 'learning', 0),
('satt', 'rassasié', 'learning', 0),
('zusammengerollt', 'roulé en boule', 'learning', 0),
('kochen/ zum Kochen bringen', 'faire bouillir', 'learning', 0),
('der Vortag', 'la veille', 'learning', 0),
('ausgehungert', 'affamé', 'learning', 0),
('lecken', 'lécher', 'learning', 0),
('das Spielzeug', 'le jouet', 'learning', 0),
('der Dreck', 'la crasse', 'learning', 0),
('sich kräuseln', 'frisotter', 'learning', 0),
('abstoßend', 'repoussant', 'learning', 0),
('abgemagert', 'efflanqué', 'learning', 0),
('düster, finster', 'lugubre', 'learning', 0),
('klasse, super', 'chouette', 'learning', 0),
('Kinderwagen', 'la poussette', 'learning', 0),
('Wiege', 'le berceau', 'learning', 0),
('etwas durchscrollen', 'faire défiler qc', 'learning', 0),
('Babykleidung', 'la layette bébé', 'learning', 0),
('sich einschreiben', 's''inscrire', 'learning', 0),
('stammeln, stottern', 'bafouiller', 'learning', 0),
('etwas kassieren', 'encaisser qc', 'learning', 0),
('schmutzig/ gemein', 'sale', 'learning', 0),
('ausschimpfen', 'gronder qn', 'learning', 0),
('Spielverderber', 'le/la rabat-joie', 'learning', 0),
('verärgert', 'agacé', 'learning', 0),
('etwas ziehen/schleppen', 'traîner qc', 'learning', 0),
('Kosten', 'les frais', 'learning', 0),
('phantasieren', 'divaguer', 'learning', 0),
('stecken bleiben', 's''enliser', 'learning', 0),
('endlos', 'interminable', 'learning', 0),
('sich ziehen/dehnen', 's''étirer', 'learning', 0),
('überschritten, abgelaufen', 'dépassé', 'learning', 0),
('vollstopfen', 'bourré', 'learning', 0),
('gut in Form', 'en pleine forme', 'learning', 0),
('von nun an', 'désormais', 'learning', 0),
('Rechnungswesen', 'la comptabilité', 'learning', 0),
('sich erschöpfen', 's''épuiser', 'learning', 0),
('an etwas klopfen', 'toquer à qc', 'learning', 0),
('keimen', 'germer', 'learning', 0),
('an sich', 'en soi', 'learning', 0);
